#! /bin/bash

. /vagrant/aws.creds

export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
export AWS_DEFAULT_REGION=$(curl --silent http://instance-data/latest/dynamic/instance-identity/document | awk -F\" '/region/ {print $4}')

ami_id=$(curl http://instance-data/latest/meta-data/ami-id)
echo deleting this AMI $ami_id
aws ec2 deregister-image  --image-id $ami_id
snapshot_id=$(aws ec2 describe-snapshots --filters Name=description,Values="*$ami_id*" | awk -F\" '/SnapshotId/ {print $4}')
echo deleting this AMI snapshot $snapshot_id
aws ec2 delete-snapshot --snapshot-id $snapshot_id
